// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxlikoyaktnuiatnjlxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bGlrb3lha3RudWlhdG5qbHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxOTE3MTIsImV4cCI6MjA1MTc2NzcxMn0.r53kOQTl40by5a3-G2FzU-zpd60FY4wVqv5kG8eUzbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);